# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

pip install pandas matplotlib seaborn openpyxl

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ===============================
# DATA CLEANING & REPORT AUTOMATION
# ===============================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------------
# STEP 1 : Load Dataset
# -------------------------------
data = pd.read_csv(
    "Sample - Superstore.csv",
    encoding="latin1",
    low_memory=False
)

print("Dataset Loaded Successfully")

# -------------------------------
# STEP 2 : Clean Column Names
# -------------------------------
data.columns = data.columns.str.strip().str.lower()

print("\nColumns:")
print(data.columns)

# -------------------------------
# STEP 3 : Data Cleaning
# -------------------------------

# Remove missing values
data = data.dropna()

# Remove duplicates
data = data.drop_duplicates()

# Convert date columns
data["order date"] = pd.to_datetime(
    data["order date"],
    format="mixed",
    errors="coerce"
)

data["ship date"] = pd.to_datetime(
    data["ship date"],
    format="mixed",
    errors="coerce"
)

print("\nData Cleaning Completed")

# -------------------------------
# STEP 4 : Feature Engineering
# -------------------------------

# Profit ratio
data["profit ratio"] = data["profit"] / data["sales"]

# Month column
data["month"] = data["order date"].dt.month

# Short product name
data["short product"] = (
    data["product name"]
    .str.split()
    .str[:2]
    .str.join(" ")
)

print("New Columns Created")

# -------------------------------
# STEP 5 : REPORT GENERATION
# -------------------------------

sales_report = data.groupby("category")["sales"].sum()
profit_report = data.groupby("region")["profit"].sum()

print("\nSales Report:")
print(sales_report)

print("\nProfit Report:")
print(profit_report)

# -------------------------------
# STEP 6 : SUMMARY INSIGHTS
# -------------------------------

print("\n----- BUSINESS SUMMARY -----")
print("Total Sales:", data["sales"].sum())
print("Total Profit:", data["profit"].sum())
print("Total Orders:", data["order id"].nunique())

# -------------------------------
# STEP 7 : DASHBOARD CREATION
# -------------------------------

plt.figure(figsize=(14,10))

# Sales by Category
plt.subplot(2,2,1)
sales_report.plot(kind="bar")
plt.title("Sales by Category")

# Profit by Region
plt.subplot(2,2,2)
profit_report.plot(kind="bar")
plt.title("Profit by Region")

# Monthly Sales
plt.subplot(2,2,3)
data.groupby("month")["sales"].sum().plot()
plt.title("Monthly Sales Trend")

# Sales vs Profit
plt.subplot(2,2,4)
sns.scatterplot(x="sales", y="profit", data=data)
plt.title("Sales vs Profit")

plt.tight_layout()

# Save dashboard image
plt.savefig("sales_dashboard.png")

plt.show()

print("\nDashboard Created")

# -------------------------------
# STEP 8 : EXPORT REPORTS
# -------------------------------

# Save cleaned data
data.to_csv("cleaned_superstore.csv", index=False)

# Excel report
with pd.ExcelWriter("Superstore_Report.xlsx") as writer:
    data.to_excel(writer, sheet_name="Cleaned Data")
    sales_report.to_excel(writer, sheet_name="Category Sales")
    profit_report.to_excel(writer, sheet_name="Region Profit")

print("\nReports Exported Successfully")

print("\nPROJECT COMPLETED ✅")

